import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../app/store';
import axios from 'axios'
export interface User {
    userInfo: {
        _id: string,
        firstName: string;
        lastName: string;
        email: string;
        phone: string;
    }
    // isLogIn: boolean;
    status: 'idle' | 'loading' | 'failed';
}

const initialState: User = {
    userInfo: {
        _id: "",
        firstName: "",
        lastName: "",
        email: "",
        phone: "",
    },
    // isLogIn: false,
    status: 'idle',
};


export const fetchUser = createAsyncThunk(
    'user/fetchUser',
    async (obj: any) => {
        const { email, password } = obj
        try {
            const response = await axios.post('/users/login', { "email": email, "password": password })
            console.log(response.data)
            return response.data;
        }
        catch (err: any) {
            console.log(err.message)
        }
    }
);


export const userReducer = createSlice({
    name: 'user',
    initialState,
    reducers: {
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchUser.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(fetchUser.fulfilled, (state, action) => {
                if (action.payload.ok == true) {
                    state.status = 'idle';
                    state.userInfo = action.payload.user;
                    // state.isLogIn = true;
                }
            })  
    },
});


export const getFirstName = (state: RootState) => state.user.userInfo.firstName;
export const getLastName = (state: RootState) => state.user.userInfo.lastName;
export const getID = (state: RootState) => state.user.userInfo._id;
export const userInfo = (state: RootState) => state.user.userInfo;
// export const getloginState = (state: RootState) => state.user.isLogIn;
export const getUserEmail = (state: RootState) => state.user.userInfo.email;
// export const getRole = (state: RootState) => state.user.userInfo.type;

export default userReducer.reducer;
